# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" # ubuntu 18

  config.vm.provider "virtualbox" do |vb|
    vb.name = "uSDN-NG Testbed" + Time.now.strftime(" %Y-%m-%d")
    vb.memory = 4096
    vb.cpus = 2
    vb.gui = true
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end

  config.vm.synced_folder "../../", "/home/vagrant/contiki-ng"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.hostname = "usdn-ng"
  config.vm.provision "shell", path: "bootstrap-vbox-with-x.sh"
  config.vm.provision "file", source: "bootstrap.sh", destination: "/home/vagrant/bootstrap.sh"
  config.vm.provision "shell", privileged: false, inline: "chmod +x bootstrap.sh && ./bootstrap.sh"
end
